title: "Jiahao Wan"
description: ""
author: " "
email: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wjhb1997.github.io" # your GitHub Pages URL
theme: minima

# Optional social links (add as needed)
# twitter_username: your_twitter
# github_username: wjhb1997

# Build settings
markdown: kramdown
